package com.horseracing.enums;

public enum FileType {
    HORSE_PHOTO,
    PASSPORT_SCAN,
    HEALTH_CERTIFICATE,
    JOCKEY_AVATAR,
    LICENSE_SCAN,
    MEDICAL_CERTIFICATE,
    DOPING_REPORT,
    HEALTH_RECORD_ATTACHMENT
}